### ISSUE TITLE
Feature request: Specifying Fractional Sampling Rates?

### ISSUE THREAD

**Issue by jnvandermeer** [sccn/cleanline#5]
I work with a system that has a sampling rate of 125.2796. It's a bluetooth-transmitted 16-channel Dry-electrode EEG. (from OpenBCI) and i check the sampling rate against the clock of the PC receiving the data using LSL timestamps. It could also mean that the computer clock of a Dell XPS13 is not as accurate as the clock in the EEG system, but I think I trust the clock of my laptop more. Both clocks, whatever their actual frequency, are at least consistent.

When I import it recorded data into EEGlab, the srate is 125. I think having fractional sampling rates in EEGLAB is normally problematic for many of the tools, and that this rounding itself should not be too much of a problem.

This all does mean that the synthesis of 50 Hz waveforms is not correct, the fractional sampling rate means that the waves changes shape throughout time due to unaccounted-for phase accumulation. However, would it be correct to think that the 50 Hz, with the weird fractional sampling rate, will just be estimated as another frequency, for example, 49.95, and that the odd sampling rate I have in the end doesn't matter as long as I scan for the proper frequency?

The thompson T Stats do a proper job estimating the 50 Hz peak, but the removal does not take away enough power. I think that my problem may also just be that the sampling rate is really slow. Another issue might be that the line noise may not be represented in the electrode leads as an exact sine wave. If that is the case, a windowed-template-based approach would be better (but much harder to program).

Up to this point I just notch-filter my data, but any thoughts would be appreciated. 

Many thanks for your time and best wishes
Johan

**Comment by arnodelorme** [comment]
This is a good point. EEGLAB should indeed allow for fractional sampling rate. Did you try the plugin zapline-plus

**Comment by jnvandermeer** [comment]
Hi Arnoud,

I tried the zapline-plus. It didn't work with matlab 2018a because matlab's basic 'mean' function has changed. But with matlab 2022a it works. 

It removes a bit of the 50 Hz, but I have to fiddle a lot with the parameters. I suspect it has something to do with a low sampling rate, or the lower amount of channels (16). I understand from the paper that the cleanup involves a bandpass and bandstop filter to partition the signal into 2, then the bandpass part is demixed and some components are thrown away.

I want to fiddle with the window sizes and thresholds to see if I can make a good correction, but I am not sure if I use all the proper parameters:
[EEG plothandles] = clean_data_with_zapline_plus_eeglab_wrapper(EEG,struct('noisefreqs',49.9, 'detailedFreqBoundsUpper', [-1, 1], 'detectionWinsize', 9))

Alternatively I can re-run zapline 3 times with standard settings, and each time a bit more of the line noise is removed.

Another thought is that the 50 Hz peak is very quite broad in the spectra, and so close to the Nyquist frequency, that I might be better served by just filtering < 45 Hz and work with that. I attach a picture of the output, in which I just used the default parameters to get rid of line noise (50 Hz).

![image](https://user-images.githubusercontent.com/2698152/202620537-e7c03783-fa2d-450f-89a0-5eda1a5e63e8.png)

**Comment by jnvandermeer** [comment]
The issue of line noise cleanup when your sampling rate is a a mere 125.281 (or some other fraction) becomes more problematic, because the 50Hz is too close the the Nyquist criterion, making the signal behave like a huge zig-zag on top of anything else.

In the end I re-implemented the cleanline method (going through the signal in windows and subtracting the sine wave) to estimate the line noise so I can inspect it and subtract it later. Instead of using Matlab's FFT to estimate the peak, amplitude and the phase, I used a model for the line noise (actually just a lambda function) and a cost function involving the STD and skewness of the residual after subtraction. Using this cost function, you then have to do a global optimization search to find the best possible amplitude, phase and frequency as inputs and then repeat this for all windows and channels. It takes more time to do the correction, but it yields pretty good corrections for my purposes and leaves the lower frequencies intact.

I think if you have a low amount of channels, the zapline-plus method becomes more challenging as spatial filters are not as good, and with a lower sampling rate, the cleanline as implemented become more challenging because FFT cannot estimate the frequency/phase with the needed accuracy. I think the FFT does work very well for sampling rates of 250 and above.

Thanks for making EEGlab and the cleanline plugins.
