### ISSUE TITLE
Issue running Clean Line Noise in PREP

### ISSUE THREAD

**Issue by chaggarty90** [sccn/cleanline#6]
I keep getting an issue when running the pipeline in a script. The script reads

**signal = struct('data', EEG.data, 'srate', EEG.srate);
   lineNoiseIn = struct('lineNoiseMethod', 'clean', ...
                             'lineNoiseChannels', 1:EEG.nbchan,...
                             'Fs', EEG.srate, ...
                            'lineFrequencies', [60 120 180 240],...
                             'p', 0.01, ...
                             'fScanBandWidth', 2, ...
                           'taperWindowStep', 1, ...
                             'tau', 100, ...
                            'pad', 2, ...
                           'fPassBand', [0 EEG.srate/2], ...
                             'maximumIterations', 10);
  [clnOutput, lineNoiseOut] = cleanLineNoise(signal, lineNoiseIn);
    EEG.data = clnOutput.data;**

The error:

**Unrecognized field name "taperBandWidth".

Error in cleanLineNoise (line 49)
hbw = lineNoiseOut.taperBandWidth/2;   % half-bandwidth

Error in Second_Preprocess_DEG_v2 (line 44)
  [clnOutput, lineNoiseOut] = cleanLineNoise(signal, lineNoiseIn);**

**Comment by arnodelorme** [comment]
Seems like you need to add "taperBandWidth" to your lineNoiseIn structure, no?

**Comment by chaggarty90** [comment]
So simple... Thanks!
