### ISSUE TITLE
Cleanline Memory Issue

### ISSUE THREAD

**Issue by jgman86** [sccn/cleanline#7]
Hey all, 

I don't know whether this is the correct repo to post in, but since I haven't found another one, I'll give it a try.

I want to use cleanline 2.0 with eeglab to correct for line noise, but everytime I call the function, my system crashes/feezes due to memory issues. Immidiatly after calling cleanline, RAM load increases to the maximum on every system I tried:

- 64 Core HPC Node; ~ 100 GB RAM (even 200 GB memory crashed)
- 16 Core home setup, 64 GB RAM
- 8 Core offcie setup, 16 GB RAM (did not expect that it works here, just for sanity)

My data is quite large, but nothing exceptional:

- Standard 32 Channel 10/20 BrainVision Recording
- 1000 HZ sampling rate 
- ca. 2,5 hours rawdata

This is my function call, which all my collegues are using, too. I'm using EEGLAB 2023.1:

```
 % Remove Line Noise of 50 Hz

   EEG = pop_cleanline(EEG, ...
       'bandwidth',2, ...              % 'Bandwidth',2,
       'chanlist',1:EEG.nbchan, ...    % 'ChanCompIndices',[1:EEEG.nbchan],'freqrange',[1
       'computepower',0, ...           % 'ComputeSpectralPower',true,
       'linefreqs',50, ...                  % 'LineFrequencies',[60 120],
       'newversion',1, ...
       'normSpectrum',0, ...           % 'NormalizeSpectrum',false,
       'p',0.01, ...                   % 'LineAlpha',0.01,
       'pad',2, ...                    % 'PaddingFactor',2,
       'plotfigures',0, ...            % 'PlotFigures',false,
       'scanforlines',1, ...           % 'ScanForLines',true,
       'sigtype','Channels', ...       % 'SignalType','Channels',
       'taperbandwidth',2, ...         %  seeting for newversion
       'tau',100, ...                  % 'SmoothingFactor',100,
       'verb',0, ...                   % 'VerboseOutput',1,
       'winsize',4, ...                % 'SlidingWinLength',EEG.pnts/EEG.srate,
       'winstep',1);                   % 'SlidingWinStep',EEG.pnts/EEG.srate

```

As I want to use the cleaned data for multiple analysis, I don't want to downsample the data for cleaning (non-of my colleagues do either).  However, even for the ICA dataset, which is downsampled to 200 Hz, the same issue persists.

I'm unsure whether this is a bug, or a property of my data, as it is quite long (1.2 GB per file).  Zapline-plus would work in theory, but I don't want to downsample to 250 - 500 Hz as recommended by the authors (e.g. for time-frequency-analysis, this would be to low for me). 

Thanks for your answers in advance ! 

greetings from Mainz

Jan

**Comment by neuromechanist** [comment]
Hi Jan,

I understand that this is a very late response, but the problem seems to be due to `'newversion',1` argument. The new version uses the parallel processing toolbox to make the processing faster. That, in turn, needs considerable RAM. There are two solutions:
1. Use the older version by having `'newversion',0` (which is currently the default).
2. Limit Matlab parpool to ~20 cores (give each core 4GB of RAM), you should have enough overhead for an hour-long EEG.

Best,
Yahya

**Comment by arnodelorme** [comment]
Thanks Yahya for responding to that user
